### ISSUE TITLE
Server code cleanup

### ISSUE THREAD

**Issue by MKKL1** [MKKL1/chat-app#24]
# Tasks:
- [ ] use uniform method names in services
- [ ] add "Id" to names of fields that use Long as type in entity classes
- [ ] make sure that all controllers use DTOs instead of entity objects
- [ ] remove unused endpoints and methods
- [ ] document endpoints
- [ ] use spring's preAuthorize in rsocket endpoints
